---

# We will look for the most specific variable files first and eventually
# end up with the least-specific files.
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- include: redhat.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- include: debian.yml
  when: ansible_os_family == 'Debian'
